### ISSUE TITLE
Supabase functions deploy randomly breaking.

### ISSUE THREAD

**Issue by stylianosnicoletti** [supabase/setup-cli#146]
# Bug report
Supabase functions deploy randomly breaking..

## Describe the bug
3 out of 10 times am getting the following during the deployment of supabase functions.

```
error: Uncaught (in promise) Error: Module not found "https://deno.land/std@0.132.0/node/internal_binding/_winerror.ts".
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)

Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```
Rerunning failed jobs, runs it again with no issues.

## To Reproduce
It's random..

## Expected behavior
Deploy the function without breaking the GitHub Action.

## System information
runs-on: ubuntu-latest
      - uses: supabase/setup-cli@v1.1.5
        with:
          version: 1.42.5

## Additional context
Tried different versions, but the problem continue to appear.

**Comment by sweatybridge** [comment]
@laktek do we need to wrap `functions deploy` with built-in retry?

**Comment by laktek** [comment]
Looks like this is happening due to network flakiness. Yeah, a retry logic here would help.

**Comment by sweatybridge** [comment]
Closing as we are now bundling functions using edge-runtime instead of deno. Feel free to reopen if this issue persists.
